### PR TITLE
Turkish Translation for CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mugurcagdas**
Hello,
I translated CONTRIBUTING.md file from EN to TR.
I will continue to translate from EN to my own language (TR) for this project.
Could you please check it?
Thanks in advance.

### CODE REVIEW

**Comment by mugurcagdas** [comment]
Could you please check it @ICA3DaR5 ?
Thanks in advance sir.

**Comment by ICA3DaR5** [comment]
I don't speak Turkish. :/

**Comment by mugurcagdas** [comment]
Hehe, you are right. It's ok. Thanks for your reply. You can trust my translate. If you merge it i would be appreciate it.

**Comment by raja-rizki** [comment]
this forced me to reject, because no review received, thanks

**Comment by mugurcagdas** [comment]
Thank you for respect my work.

**Comment by mugurcagdas** [comment]
@raja-rizki  I am asking you, how my national people can see my translated document? It is not logical, many people translated this project and contributions was merged before.
May I ask why did you closed the PR?
Thanks in advance. :/

**Comment by ICA3DaR5** [comment]
@mugurcagdas I don't have merge rights. Probably @dckc can do it?

**Pull request merged**
