### PR TITLE
 translation to indonesia|userstory.md 

### PR DESCRIPTION
**Pull request by raja-rizki**

### CODE REVIEW

**Comment by lapin7** [comment]
Hi @raja-rizki 
Please accept https://github.com/rchain/Members/invitations
and https://groups.google.com/forum/#!pendingmember/rchain/join

**Comment by raja-rizki** [comment]
hi @lapin7  
the instructions are ready for me to follow

**Comment by lapin7** [comment]
Please send your email to ops@rchain.coop


--
Cheers,
HJ

**Comment by raja-rizki** [comment]
done :+1:

**Pull request merged**
