### PR TITLE
Tagalog Translation (tl) for CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by caratzky**
Hello, @BelovedAquila, this is caratzky. I'm a Utopian contributor for Filipino/Tagalog Translations and I'm rewarded well by the organization. Hope this helps. Your approval will be a great help to me. I'm still on the process of translating into Filipino the transcript of the video you shared to me.

This one - I translated this file for the sake of all Filipino developers. This file is located directly in the master folder.

Best Regards,
caratzky

### CODE REVIEW

**Comment by BelovedAquila** [comment]
Wow great job friend firstly start by removing the English version of it and make it a single doc of just Filipino, to make it concised. Are you on discord or telegram? Would love collaborating with you. Cheers!

**Comment by caratzky** [comment]
I'm both on discord and telegram, @BelovedAquila :)

**Comment by caratzky** [comment]
Can't you merge this commit yet? I can't be rewarded if I don't get ur approval for my translation for CONTRIBUTING.md. Hehe. God bless @BelovedAquila :)

**Comment by lapin7** [comment]
@caratzky 
plz join https://groups.google.com/forum/#!managemembers/rchain/join
and accept https://github.com/rchain/Members/invitations
and send your email to ops@rchain.coop

@BelovedAquila do you want to play a role in the registration of new RAM's? let's create a new issue "O> registration of new RAM's"

**Comment by BelovedAquila** [comment]
@caratzky how do I look you up? Or just look me up @BelovedAquila. Thank you.

@lapin7 gladly will 😆,Thank you.

**Comment by caratzky** [comment]
Yes, Thank you @BelovedAquila  :)

**Pull request merged**
