### PR TITLE
Cebuano Translation (ceb) for CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by codygee237**
Hi, this is codygee237. I'm a Utopian contributor for Cebuano Translations. I'm hoping for your positive response. Thank you

Best Regards,
codygee237

### CODE REVIEW

**Comment by codygee237** [comment]
Thank you @caratzky! I appreciate it. More power to you.

**Comment by dbucci24** [comment]
@caratzky hey, this project need spanish translation? i want to contribute

**Comment by caratzky** [comment]
Sure @dbucci24 but you have to follow the guides and rules

**Comment by codygee237** [comment]
Okay Sir, I will repair it immediately.

**Pull request merged**
