### PR TITLE
partial translation to [indonesian] ~ [496 words]

### PR DESCRIPTION
**Pull request by raja-rizki**

### CODE REVIEW

**Comment by caratzky** [comment]
@raja-rizki  please do not delete the original english files. You should make new files and submit them as 
 pull request. @BelovedAquila  please take note of this.  Or please react If I said anything wrong.

**Comment by raja-rizki** [comment]
please forgive
that is my mistake

**Comment by caratzky** [comment]
I suggest you make a new file on the folder where the source file is located. You'll just have to copy the codes in the source file and paste it  to the new one and translate them one by one. Then upon completion, you choose the option of making a separate branch and submitting it as a pull request. 

God bless you @raja-rizki  :)

**Comment by raja-rizki** [comment]
good info, thanks

Pada tanggal 12 Feb 2018 11.56 AM, "CARATZKY" <notifications@github.com>
menulis:

**Pull request merged**
