### PR TITLE
Partial Cebuano translation for dictionary.md

### PR DESCRIPTION
**Pull request by agentzero1**
Part 1 of Cebuano translation for dictionary.md. Almost 1500 translated words

### CODE REVIEW

**Comment by kitblake** [comment]
Hey @agentzero1, this document is in an unfinished state and it's too early to start translating it. 

Please keep your work, but first let's get a final. This requires input from technical people, but it's not a priority at the moment.

**Comment by agentzero1** [comment]
Do you mean Cebuano translation is not priority now ?

**Comment by kitblake** [comment]
No, I mean the whole document is not a priority now. It's been dormant for awhile and the techies have higher priorities, so we content workers have to be patient.

**Comment by agentzero1** [comment]
Okay, Can you tell me what document is priority ?

**Comment by agentzero1** [comment]
Or any suggestion what document shoukd I use

**Pull request closed without merging**
